### ISSUE TITLE
tech& 블로그 링크 추가

### ISSUE THREAD

**Issue by loophy-cho** [kakaoenterprise/kakaoenterprise.github.io#11]
tech& 블로그 사이트와 연계를 위해, 현재 메뉴에 있는 'deepdive'를 tech&(https://tech.kakaoenterprise.com) 블로그 링크로 교체하면 좋을 것 같습니다.

**Comment by loophy-cho** [comment]
아래와 같이 교체될 예정입니다.

(교체안)
- 명칭: Tech&
- url: https://tech.kakaoenterprise.com

**Comment by bohyunjung** [comment]
#16 에서 해결
