### ISSUE TITLE
SIGIR 논문명 수정 

### ISSUE THREAD

**Issue by minwoo** [kakaoenterprise/kakaoenterprise.github.io#64]
https://kakaoenterprise.github.io/papers/sigir-rl-irs

위의 논문이 최종 발표에는 이름이 변경되었습니다.
`Towards Validating Long-Term User Feedbacks in Interactive Recommendation Systems`
https://dl.acm.org/doi/abs/10.1145/3477495.3531869

또한 논문이 Best Short Paper Honorable Mention에 수상하였이니 내용을 추가하면 좋을것 같습니다.
https://sigir.org/sigir2022/program/best-paper-awards/

**Comment by loophy-cho** [comment]
안녕하세요?
논문제목과 abstract 내용을 수정 중이었으나, 반영이 조금 늦게 되었습니다.
논문정보를 포함해 의견주신 Best Short Paper Honorable Mention 까지 내용 업데이트 완료하였습니다.
감사합니다.
